<a href="https://colab.research.google.com/github/roseann47625/BSIS-2A-CABANG-ROSE-ANN-E/blob/main/profelective1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/roseann47625/cabangroseann_bsis3/refs/heads/main/product_data_with_missing_values.csv')

In [18]:
df.head()

    Category   Price  Rating  Stock  Discount
0      Books  124.31     3.2   61.0      35.6
1       Toys  343.22     2.5  185.0      40.5
2  Groceries  306.95     4.9   51.0      17.4
3       Toys  417.43     NaN   11.0       4.8
4       Toys   90.82     3.9    NaN      47.0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  47 non-null     object
 1   Price     49 non-null     float64
 2   Rating    47 non-null     float64
 3   Stock     48 non-null     float64
 4   Discount  49 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [20]:
print(df.isnull().sum())

Category    3
Price       1
Rating      3
Stock       2
Discount    1
dtype: int64

In [21]:
df = df.drop(columns=['Discount'])

In [28]:
df.head()

    Category   Price  Rating  Stock
0      Books  124.31     3.2   61.0
1       Toys  343.22     2.5  185.0
2  Groceries  306.95     4.9   51.0
3       Toys  417.43     NaN   11.0
6  Groceries   95.21     2.0  130.0

In [29]:
df = df.drop(df.index[4])

In [30]:
df.head()

    Category   Price  Rating  Stock
0      Books  124.31     3.2   61.0
1       Toys  343.22     2.5  185.0
2  Groceries  306.95     4.9   51.0
3       Toys  417.43     NaN   11.0
7  Groceries  378.90     NaN  112.0

In [31]:
df = df.fillna("N/A")

In [32]:
df.head()

    Category   Price Rating  Stock
0      Books  124.31    3.2   61.0
1       Toys  343.22    2.5  185.0
2  Groceries  306.95    4.9   51.0
3       Toys  417.43    N/A   11.0
7  Groceries   378.9    N/A  112.0